# Generated by Django 3.1.5 on 2021-10-05 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(max_length=255, verbose_name='Название')),
                ('slugCategory', models.SlugField(default=None, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameKitchen', models.CharField(max_length=255, verbose_name='Наименование')),
                ('imageKitchen', models.ImageField(upload_to='images/kitchen/', verbose_name='Изображение')),
                ('slugKitchen', models.SlugField(default=None, unique=True)),
            ],
            options={
                'verbose_name': 'Кухня',
                'verbose_name_plural': 'Кухни',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания рецепта')),
                ('nameRecipe', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('timeofCreation', models.TimeField(verbose_name='Время готовки')),
                ('count', models.SmallIntegerField(verbose_name='Количество порций')),
                ('imageRecipe', models.ImageField(upload_to='images/recipe/', verbose_name='Изображение готового блюда')),
                ('slugRecipe', models.SlugField(default=None, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recept.category', verbose_name='Категория')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recept.kitchen', verbose_name='Кухня')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleStage', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('discription', models.TextField(blank=True, verbose_name='Описание')),
                ('imageStage', models.ImageField(upload_to='images/stage/', verbose_name='Изображение')),
                ('slugStage', models.PositiveIntegerField(default=1, verbose_name='Шаг')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recept.recipe')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameIngredient', models.CharField(max_length=255, verbose_name='Название')),
                ('count', models.CharField(max_length=255, verbose_name='Количество/текст')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recept.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recept.recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
