# Generated by Django 3.1.5 on 2021-10-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slugRecipe',
        ),
    ]
